---
abstract: 'Read/write 7z , zip , ISO9960 and other archives'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-SevenZip
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '0'
  Exporter: '5'
  File::Basename: '0'
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0'
  IPC::Open3: '0'
  Path::Class: '0'
  Test::More: '0'
  Time::Piece: '0'
resources:
  repository: https://github.com/Corion/archive-sevenzip
version: '0.05'
